language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mrgrenier123/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mrgrenier123/docker-react npm run test    

deploy:
    provider: elasticbeanstalk
    region:  "us-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-west-2-887879401527"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY